package club.fcim.usedbooktrade.mybatis.model;

import java.util.Date;

public class UsedbookNotes {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usedbook_notes.id
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usedbook_notes.name
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usedbook_notes.grade
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	private String grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usedbook_notes.school
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	private String school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usedbook_notes.contact
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usedbook_notes.type
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usedbook_notes.updatetime
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usedbook_notes.id
	 * @return  the value of usedbook_notes.id
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usedbook_notes.id
	 * @param id  the value for usedbook_notes.id
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usedbook_notes.name
	 * @return  the value of usedbook_notes.name
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usedbook_notes.name
	 * @param name  the value for usedbook_notes.name
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usedbook_notes.grade
	 * @return  the value of usedbook_notes.grade
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usedbook_notes.grade
	 * @param grade  the value for usedbook_notes.grade
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usedbook_notes.school
	 * @return  the value of usedbook_notes.school
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usedbook_notes.school
	 * @param school  the value for usedbook_notes.school
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public void setSchool(String school) {
		this.school = school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usedbook_notes.contact
	 * @return  the value of usedbook_notes.contact
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usedbook_notes.contact
	 * @param contact  the value for usedbook_notes.contact
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usedbook_notes.type
	 * @return  the value of usedbook_notes.type
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usedbook_notes.type
	 * @param type  the value for usedbook_notes.type
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usedbook_notes.updatetime
	 * @return  the value of usedbook_notes.updatetime
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usedbook_notes.updatetime
	 * @param updatetime  the value for usedbook_notes.updatetime
	 * @mbg.generated  Sun Oct 16 20:18:31 CST 2016
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}